### ISSUE TITLE
Brew SOLR seems hosed

### ISSUE THREAD

**Issue by MetaBureau** [BrianGilbert/OSXAegirInstaller#43]
Suggest perhaps you use the one available here: https://www.drupal.org/documentation/modules/search/quick-start-solr-4

**Comment by BrianGilbert** [comment]
@MetaBureau The reson solr has stopped working for you is most likley because it now requires Java 7+  I had to uninstall Apples Java 6 and link up so that Oracles java 8 was the one used when you ran java at cli.. I used this as a reference http://www.cc.gatech.edu/~simpkins/teaching/gatech/cs2340/guides/java7-macosx.html

**Comment by BrianGilbert** [comment]
@MetaBureau Install script now updated so that solr will work on a clean installation, you should be able to figure out what you need to do from the changes
